.PHONY: clean All

All:
	@echo "----------Building project:[ AP01 hidding the attributes - Debug ]----------"
	@"$(MAKE)" -f  "AP01 hidding the attributes.mk"
clean:
	@echo "----------Cleaning project:[ AP01 hidding the attributes - Debug ]----------"
	@"$(MAKE)" -f  "AP01 hidding the attributes.mk" clean
